//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sporsalonu.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class etkinlikbasvuruları
    {
        public int etkinlikid { get; set; }
        public string etkinlikadı { get; set; }
        public string başvuranadsoyad { get; set; }
    }
}
