//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sporsalonu.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int iletisimid { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public string Açıklama { get; set; }
    }
}
