//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sporsalonu.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class üyebilgidetay
    {
        public int bilgiid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel { get; set; }
        public string boy { get; set; }
        public string kilo { get; set; }
        public string ölçüm { get; set; }
        public string tarih { get; set; }
    }
}
